<footer>
	<section class="footer_section">	
		<h2>Ocean Cruise</h2>
		<img id="footer_logo" src="images/logo.png" alt="logo">
	</section>
	<section class="footer_section">
		<h2>Quick Links</h2>
		<ul>
			<li><a href="index.php" >Home</a></li>
			<li><a href="product.php">Product</a></li>
			<li><a href="enquire.php">Enquiry</a></li>
			<li><a href="about.php">About</a></li>
    		<li><a href="enhancements.php">Enhancements</a></li>
    		<li><a href="enhancements2.php">Enhancements2</a></li>
    		<li><a href="manager.php">Manager</a></li>
   		</ul>
	</section>
	<section class="footer_section">
		<h2>Contact Details</h2>
		<ul>
			<li><a href="tel:+61444222666" target="_blank">Phone: +61 444 222 666</a></li>
			<li><a href="mailto:info@oceancruise.com.au" target="_blank">Mail: info@oceancruise.com.au</a></li>
			<li><a href="https://goo.gl/maps/HqiTQSYEg3tBuFpc6" target="_blank">Address: Melbourne, Victoria</a></li>
		</ul>
	</section>
</footer>